/**
 * Mock data for development and testing.
 * The lecture schema includes whiteboard fields (v2).
 */

export const MOCK_DATA = [
  {
    id: '1',
    title: "Atomic bombshell in call of duty",
    date: "Jan 24 2025",
    duration: "15min",
    category: "Physics",
    isFavorite: false,
    image: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/JWx5b4z3d8/qftcx6me_expires_30_days.png",
    // Audio/Transcript fields
    audioUri: null,
    transcribedText: '',
    transcriptSegments: [],
    summary: '',
    flashcards: [],
    // Whiteboard fields (v2)
    whiteboardSnapshot: null,
    conceptGraph: null,
    whiteboardSyncStatus: 'synced',
    lastWhiteboardSync: null,
    schemaVersion: 2,
  },
  {
    id: '2',
    title: "Quantum Physics Introduction",
    date: "Jan 24 2025",
    duration: "45min",
    category: "Physics",
    isFavorite: true,
    image: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/JWx5b4z3d8/dogh1pny_expires_30_days.png",
    audioUri: null,
    transcribedText: '',
    transcriptSegments: [],
    summary: '',
    flashcards: [],
    whiteboardSnapshot: null,
    conceptGraph: null,
    whiteboardSyncStatus: 'synced',
    lastWhiteboardSync: null,
    schemaVersion: 2,
  },
  {
    id: '3',
    title: "Organic Chemistry Basics",
    date: "Jan 25 2025",
    duration: "30min",
    category: "Chemistry",
    isFavorite: false,
    image: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/JWx5b4z3d8/4h3iuzvx_expires_30_days.png",
    audioUri: null,
    transcribedText: '',
    transcriptSegments: [],
    summary: '',
    flashcards: [],
    whiteboardSnapshot: null,
    conceptGraph: null,
    whiteboardSyncStatus: 'synced',
    lastWhiteboardSync: null,
    schemaVersion: 2,
  },
  {
    id: '4',
    title: "Calculus II: Integration",
    date: "Jan 26 2025",
    duration: "60min",
    category: "Math",
    isFavorite: true,
    image: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/JWx5b4z3d8/88t1ga5l_expires_30_days.png",
    audioUri: null,
    transcribedText: '',
    transcriptSegments: [],
    summary: '',
    flashcards: [],
    whiteboardSnapshot: null,
    conceptGraph: null,
    whiteboardSyncStatus: 'synced',
    lastWhiteboardSync: null,
    schemaVersion: 2,
  },
];

export const FILTERS = ["All", "Favorites", "Physics"];
